const product = [
  {
    id: 0,
    image: 'images/image1.png',
    title: 'Bretling Navitime 01 | Leather  ',
    details: 'Breitling SA Navitimer 01 Watch Chronograph with black leather strip',
    price: 470,
  },
  {
    id: 1,
    image: 'images/image2.png',
    title: 'G-Shock WR220BAR ',
    details: 'G-Shock WR220BAR Solar-powered watch Casio Wave Ceptor',
    price: 550,
  },
  {
    id: 2,
    image: 'images/image3.png',
    title: 'Rolex Datejust ',
    details: 'Rolex Datejust Submariner Watch Colored gold',
    price: 480,
  },
  {
    id: 3,
    image: 'images/image4.png',
    title: 'Rolex GMT Master II ',
    details: 'Rolex Submariner Rolex Daytona Rolex Datejust Rolex GMT Master II',
    price: 550,
  },
  {
    id: 4,
    image: 'images/image5.png',
    title: 'Cartier Tank | Blue ',
    details: "Blue Cartier Tank watch men's watch",
    price: 500,
  },
  {
    id: 5,
    image: 'images/image6.png',
    title: ' Tissot',
    details: 'Tissot Luxury mechanical watch',
    price: 650,
  },
  {
    id: 6,
    image: 'images/image7.png',
    title: ' G-Shock Frogman ',
    details: 'Casio G-Shock Frogman Watch Clock',
    price: 500,
  },
  {
    id: 7,
    image: 'images/image8.png',
    title: ' Tissot Seiko',
    details: 'Chronograph Jaeger-LeCoultre Tissot Seiko, Aristocrat watch',
    price: 770,
  },
  {
    id: 8,
    image: 'images/image1.png',
    title: 'Bretling Navitime 01 | Leather  ',
    details: 'Breitling SA Navitimer 01 Watch Chronograph with black leather strip',
    price: 470,
  },
  {
    id: 9,
    image: 'images/image2.png',
    title: 'G-Shock WR220BAR ',
    details: 'G-Shock WR220BAR Solar-powered watch Casio Wave Ceptor',
    price: 550,
  },
  {
    id: 10,
    image: 'images/image3.png',
    title: 'Rolex Datejust ',
    details: 'Rolex Datejust Submariner Watch Colored gold',
    price: 480,
  }
];
